services:

  web:
    image: node
    command: /bin/sh -c "while sleep 1000; do :; done"
    networks:
      - servers
    volumes:
      - ./:/app
    ports:
      - 3002:3000
    working_dir: /app

networks:
  servers:
    # driver: bridge
    external: true